matrix:
  include:
    - language: node_js
      node_js:
        - 6.17.1
      sudo: true
      before_install: sudo apt update
      install: 
        - ./csv-dependencies.bash
        - ./xml-dependencies.bash
      script: ./integrity-check.bash
    - language: ruby
      rvm:
        - 2.5.0
      sudo: true
      before_install: sudo apt update
      install: 
        - ./csv-dependencies.bash
        - ./xml-dependencies.bash
      script: ./integrity-check.bash
    - language: perl
      perl:
        - 5.18.4
      install: 
        - ./csv-dependencies.bash
        - ./xml-dependencies.bash
      script: ./integrity-check.bash
    - language: scala
      scala:
        - 2.11.11
      install: 
        - ./csv-dependencies.bash
        - ./xml-dependencies.bash
      script: ./integrity-check.bash
    - language: java
      jdk:
        - openjdk8
      install: 
        - ./csv-dependencies.bash
        - ./xml-dependencies.bash
      script: ./integrity-check.bash
    - language: python
      python:
        - 2.7
      install: 
        - ./csv-dependencies.bash
        - ./xml-dependencies.bash
      script: ./integrity-check.bash
    - language: minimal
      before_install: sudo apt update
      install: 
        - ./csv-dependencies.bash
        - ./xml-dependencies.bash
      script: ./integrity-check.bash