matrix:
  include:
    - language: node_js
      node_js:
        - 6.17.1
      sudo: true
      script: ./js-checks.bash
    - language: ruby
      rvm:
        - 2.5.0
      sudo: true
      script: ./ruby-checks.bash
    - language: perl
      os: linux
      dist: precise
      perl:
        - 5.18.4
      script: ./perl-checks.bash
    - language: scala
      scala:
        - 2.11.11
      script: ./scala-checks.bash
    - language: java
      jdk:
        - openjdk8
      script: ./java-checks.bash
    - language: python
      python:
        - 2.7
      script: ./python-checks.bash
    - language: minimal
      before_install: sudo apt update
      install: 
        - ./csv-dependencies.bash
        - ./xml-dependencies.bash
      script: ./misc-checks.bash