matrix:
  include:
    - language: node_js
      node_js:
        - 10.15.3
      sudo: true
      before_install: sudo apt update
      install: 
        - ./csv-dependencies.bash
        - ./xml-dependencies.bash
      script: ./integrity-check.bash
    - language: ruby
      rvm:
        - 2.5.0
      sudo: true
      before_install: sudo apt update
      install: 
        - ./csv-dependencies.bash
        - ./xml-dependencies.bash
      script: ./integrity-check.bash
    - language: minimal
      before_install: sudo apt update
      install: 
        - ./csv-dependencies.bash
        - ./xml-dependencies.bash
      script: ./integrity-check.bash