sudo: true
matrix:
  include:
    - language: node_js
      node_js:
        - "10.15.3"
      install: apt install golang-go
      before_script: export PATH="$PATH:$HOME/go/bin"
      script: ./integrity-check.bash
    - language: ruby
      rvm:
        - 2.5.0
      install: apt install golang-go
      before_script: export PATH="$PATH:$HOME/go/bin" 
      script: ./integrity-check.bash
